# Generated by Django 3.0 on 2023-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0004_auto_20230704_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='syear',
            field=models.CharField(choices=[('0', '----- Select Year -----'), ('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='0', max_length=3),
        ),
    ]
