# Generated by Django 3.0 on 2023-07-10 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0008_auto_20230708_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentst',
            name='stactive',
            field=models.CharField(choices=[('4', 'Not Verified'), ('3', 'Verified')], default='4', max_length=3),
        ),
    ]
