# Generated by Django 3.0 on 2023-07-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0009_assignmentst_stactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upfe',
            field=models.ImageField(default='sample.png', upload_to='Profiles/'),
        ),
    ]
