# Generated by Django 3.0 on 2023-06-19 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0002_auto_20230619_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll',
            new_name='sroll',
        ),
    ]
