# Generated by Django 3.0 on 2023-06-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SampleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='age',
            new_name='sage',
        ),
    ]
