# Generated by Django 3.0 on 2023-07-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0006_assignmentt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentt',
            name='ayear',
            field=models.IntegerField(choices=[(0, '----- Select Year -----'), (1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=0, max_length=5),
        ),
    ]
