# Generated by Django 3.0 on 2023-07-03 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tage', models.IntegerField()),
                ('tgr', models.CharField(choices=[('k', 'Select Your Gender'), ('M', 'Male'), ('F', 'Female')], default='k', max_length=5)),
                ('tbranch', models.CharField(choices=[('G', '----- Select Branch -----'), ('CSE', 'Computer Science and Engineering'), ('ECE', 'Electrical and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIVIL', 'Civil Engineering')], default='G', max_length=6)),
                ('tsubject', models.CharField(max_length=10)),
                ('texpr', models.IntegerField()),
                ('tdesg', models.CharField(max_length=10)),
                ('tstatus', models.BooleanField(default=0)),
                ('tch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('sgr', models.CharField(choices=[('h', 'Select Your Gender'), ('M', 'Male'), ('F', 'Female')], default='h', max_length=5)),
                ('sbranch', models.CharField(choices=[('G', '----- Select Branch -----'), ('CSE', 'Computer Science and Engineering'), ('ECE', 'Electrical and Communication Engineering'), ('EEE', 'Electrical and Electronics Engineering'), ('CIVIL', 'Civil Engineering')], default='G', max_length=6)),
                ('syear', models.CharField(choices=[(0, '----- Select Year -----'), (1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default='0', max_length=3)),
                ('sstatus', models.BooleanField(default=0)),
                ('std', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
