# Generated by Django 3.0 on 2023-07-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ASMApp', '0003_auto_20230704_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='tdesg',
            field=models.CharField(max_length=50),
        ),
    ]
