# Generated by Django 3.0 on 2023-06-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=15)),
                ('sname', models.CharField(max_length=30)),
                ('syear', models.CharField(max_length=5)),
                ('sbranch', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
    ]
